import React from "react";
import "./landing-hero.css";

export const HeroSectionThree = (props) => {
  return (
    <div className="landing1-container">
      <div className="landing1-landing1">
        <div className="landing1-frame73">
          <div className="landing1-group22">
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-nmeg.svg"
              className="landing1-vector"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-l9vl.svg"
              className="landing1-vector01"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-pju.svg"
              className="landing1-vector02"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-68se.svg"
              className="landing1-vector03"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-xqaz.svg"
              className="landing1-vector04"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-vawq.svg"
              className="landing1-vector05"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-cbz.svg"
              className="landing1-vector06"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-j2ds.svg"
              className="landing1-vector07"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-m1c.svg"
              className="landing1-vector08"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-etvg.svg"
              className="landing1-vector09"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-nur.svg"
              className="landing1-vector10"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-xi3.svg"
              className="landing1-vector11"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-1xx.svg"
              className="landing1-vector12"
            />
          </div>
          <div className="landing1-group23">
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-mvxt.svg"
              className="landing1-vector13"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-243u.svg"
              className="landing1-vector14"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-klbo.svg"
              className="landing1-vector15"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-y2in.svg"
              className="landing1-vector16"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-fo4p.svg"
              className="landing1-vector17"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-iz0f.svg"
              className="landing1-vector18"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-qq0h.svg"
              className="landing1-vector19"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-elmb.svg"
              className="landing1-vector20"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-5og.svg"
              className="landing1-vector21"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-oxbb.svg"
              className="landing1-vector22"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-c0rh.svg"
              className="landing1-vector23"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-4dozs.svg"
              className="landing1-vector24"
            />
            <img
              alt="Vector1365"
              src="/playground_assets/vector1365-k2x8.svg"
              className="landing1-vector25"
            />
          </div>
        </div>
        <img
          alt="Vector1365"
          src="/playground_assets/vector1365-z3bp.svg"
          className="landing1-vector26"
        />
        <span className="landing1-text ParagraphLarge-18px">
          <span>
            We are a tech agency specializing in creating online presence for
            healthcare and event planning businesses. In today&apos;s digital
            age, having a strong online presence is crucial to the success of
            any business, and we are here to help you achieve just that.
          </span>
        </span>
        <div className="landing1-frame72">
          <span className="landing1-text02">
            <span>Health and Event</span>
          </span>
          <span className="landing1-text04 Displayxsmall-44px">
            <span className="landing1-text05">
              Elevate Your Online Presence with Tech Solutions for
              <span />
            </span>
            <span className="landing1-text06"> Healthcare </span>
            <span className="landing1-text07">
              and <span />
            </span>
            <span className="landing1-text08">Event</span>
            <span> Planning</span>
          </span>
        </div>
        <button className="landing1-button">
          <span className="landing1-text10 LabelSmall-14px">
            <span>Contact Us</span>
          </span>
        </button>
        <img
          alt="Vector1365"
          src="/playground_assets/vector1365-vvvn.svg"
          className="landing1-vector27"
        />
        <img
          alt="Rectangle131365"
          src="/playground_assets/rectangle131365-eimf-200h.png"
          className="landing1-rectangle13"
        />
        <div className="landing1-frame75">
          <img
            alt="unsplashM4Xloxsg0Gw1365"
            src="/playground_assets/unsplashm4xloxsg0gw1365-y8hg-400w.png"
            className="landing1-unsplash-m-xloxsg-gw"
          />
        </div>
        <div className="landing1-group10">
          <div className="landing1-frame74">
            <div className="landing1-frame58">
              <div className="landing1-frame54">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-u9r9-200h.png"
                  className="landing1-ellipse10"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-exqd-200h.png"
                  className="landing1-ellipse11"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-rrcx-200h.png"
                  className="landing1-ellipse15"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-gah-200h.png"
                  className="landing1-ellipse12"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-nfj-200h.png"
                  className="landing1-ellipse13"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-a5ht-200h.png"
                  className="landing1-ellipse14"
                />
              </div>
              <div className="landing1-frame55">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-pixs-200h.png"
                  className="landing1-ellipse1001"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-2nuk-200h.png"
                  className="landing1-ellipse1101"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-09n-200h.png"
                  className="landing1-ellipse1501"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-llt-200h.png"
                  className="landing1-ellipse1201"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-iel-200h.png"
                  className="landing1-ellipse1301"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-im0p-200h.png"
                  className="landing1-ellipse1401"
                />
              </div>
              <div className="landing1-frame56">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-y0h-200h.png"
                  className="landing1-ellipse1002"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-dxgc-200h.png"
                  className="landing1-ellipse1102"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-bv2-200h.png"
                  className="landing1-ellipse1502"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-kt4n-200h.png"
                  className="landing1-ellipse1202"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-4vcl-200h.png"
                  className="landing1-ellipse1302"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-xg9-200h.png"
                  className="landing1-ellipse1402"
                />
              </div>
              <div className="landing1-frame57">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-7hem-200h.png"
                  className="landing1-ellipse1003"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-jtzi-200h.png"
                  className="landing1-ellipse1103"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-s8ac-200h.png"
                  className="landing1-ellipse1203"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-y02-200h.png"
                  className="landing1-ellipse1303"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-glda-200h.png"
                  className="landing1-ellipse1403"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-705k-200h.png"
                  className="landing1-ellipse1503"
                />
              </div>
              <div className="landing1-frame581">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-visu-200h.png"
                  className="landing1-ellipse1004"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-gqc-200h.png"
                  className="landing1-ellipse1104"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-9ujc-200h.png"
                  className="landing1-ellipse1504"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-5xwc-200h.png"
                  className="landing1-ellipse1204"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-ngph-200h.png"
                  className="landing1-ellipse1304"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-wnts-200h.png"
                  className="landing1-ellipse1404"
                />
              </div>
              <div className="landing1-frame59">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-f7ba-200h.png"
                  className="landing1-ellipse1005"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-2mk9-200h.png"
                  className="landing1-ellipse1105"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-ylij-200h.png"
                  className="landing1-ellipse1505"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-4kta-200h.png"
                  className="landing1-ellipse1205"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-1jqs-200h.png"
                  className="landing1-ellipse1305"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-zd0g-200h.png"
                  className="landing1-ellipse1405"
                />
              </div>
            </div>
            <div className="landing1-frame591">
              <div className="landing1-frame541">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-jetv-200h.png"
                  className="landing1-ellipse1006"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-2id-200h.png"
                  className="landing1-ellipse1106"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-wjit-200h.png"
                  className="landing1-ellipse1506"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-v9ln-200h.png"
                  className="landing1-ellipse1206"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-maa5-200h.png"
                  className="landing1-ellipse1306"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-pb8l-200h.png"
                  className="landing1-ellipse1406"
                />
              </div>
              <div className="landing1-frame551">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-88f-200h.png"
                  className="landing1-ellipse1007"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-w1e-200h.png"
                  className="landing1-ellipse1107"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-fca-200h.png"
                  className="landing1-ellipse1507"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-3ng-200h.png"
                  className="landing1-ellipse1207"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-tm9l-200h.png"
                  className="landing1-ellipse1307"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-v8l-200h.png"
                  className="landing1-ellipse1407"
                />
              </div>
              <div className="landing1-frame561">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-uxw-200h.png"
                  className="landing1-ellipse1008"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-i2og-200h.png"
                  className="landing1-ellipse1108"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-mzql-200h.png"
                  className="landing1-ellipse1508"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-9i9j-200h.png"
                  className="landing1-ellipse1208"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-zuup-200h.png"
                  className="landing1-ellipse1308"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-xa2g-200h.png"
                  className="landing1-ellipse1408"
                />
              </div>
              <div className="landing1-frame571">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-s9gi-200h.png"
                  className="landing1-ellipse1009"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-grkl-200h.png"
                  className="landing1-ellipse1109"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-xo1-200h.png"
                  className="landing1-ellipse1209"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-un69-200h.png"
                  className="landing1-ellipse1309"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-a9c-200h.png"
                  className="landing1-ellipse1409"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-ka3-200h.png"
                  className="landing1-ellipse1509"
                />
              </div>
              <div className="landing1-frame582">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-2fn-200h.png"
                  className="landing1-ellipse1010"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-m8nh-200h.png"
                  className="landing1-ellipse1110"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-wd1t-200h.png"
                  className="landing1-ellipse1510"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-x3hn-200h.png"
                  className="landing1-ellipse1210"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-ttx-200h.png"
                  className="landing1-ellipse1310"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-h5gq-200h.png"
                  className="landing1-ellipse1410"
                />
              </div>
              <div className="landing1-frame592">
                <img
                  alt="Ellipse101365"
                  src="/playground_assets/ellipse101365-ekr9-200h.png"
                  className="landing1-ellipse1011"
                />
                <img
                  alt="Ellipse111365"
                  src="/playground_assets/ellipse111365-61ak-200h.png"
                  className="landing1-ellipse1111"
                />
                <img
                  alt="Ellipse151365"
                  src="/playground_assets/ellipse151365-d769-200h.png"
                  className="landing1-ellipse1511"
                />
                <img
                  alt="Ellipse121365"
                  src="/playground_assets/ellipse121365-ds4j-200h.png"
                  className="landing1-ellipse1211"
                />
                <img
                  alt="Ellipse131365"
                  src="/playground_assets/ellipse131365-ru9m-200h.png"
                  className="landing1-ellipse1311"
                />
                <img
                  alt="Ellipse141365"
                  src="/playground_assets/ellipse141365-gewd-200h.png"
                  className="landing1-ellipse1411"
                />
              </div>
            </div>
          </div>
        </div>
        <div className="landing1-frame76">
          <img
            alt="unsplashQKdjKxntH81365"
            src="/playground_assets/unsplashqkdjkxnth81365-evwf-400w.png"
            className="landing1-unsplash--kdj-kxnt-h8"
          />
        </div>
        <div className="landing1-indicator">
          <img
            alt="Ellipse91365"
            src="/playground_assets/ellipse91365-rf8s-200h.png"
            className="landing1-ellipse9"
          />
          <img
            alt="Ellipse91365"
            src="/playground_assets/ellipse91365-e4u7-200h.png"
            className="landing1-ellipse91"
          />
          <img
            alt="Ellipse91365"
            src="/playground_assets/ellipse91365-fb11-200h.png"
            className="landing1-ellipse92"
          />
        </div>
      </div>
    </div>
  );
};
