import react from "react";
import "./landing.css";

export const HeroSectionTwo = (props) => {
  return (
    <div className="landing-container">
      <div className="landing-landing">
        <img
          src="/playground_assets/vector1365-711.svg"
          alt="Vector1365"
          className="landing-vector"
        />
        <button className="landing-textand-button">
          <div className="landing-frame52">
            <span className="landing-text ParagraphLarge-18px">
              <span>Health</span>
            </span>
            <span className="landing-text02 Displayxsmall-44px">
              <span className="landing-text03">
                Enhancing Healthcare
                <span />
              </span>
              <span className="landing-text04">Experience</span>
              <span> with Technology</span>
            </span>
          </div>
          <div className="landing-frame53">
            <span className="landing-text06 ParagraphLarge-18px">
              <span>
                Our solutions span across the healthcare industry, including
                hospitals, clinics, and health insurance companies.
              </span>
            </span>
            <button className="landing-button">
              <span className="landing-text08">
                <span>Contact Us Now</span>
              </span>
            </button>
          </div>
        </button>
        <img
          src="/playground_assets/frame311365-7jt.svg"
          alt="Frame311365"
          className="landing-frame31"
        />
        <div className="landing-group10">
          <div className="landing-frame58">
            <div className="landing-frame54">
              <img
                src="/playground_assets/ellipse101365-jxcg-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse10"
              />
              <img
                src="/playground_assets/ellipse111365-s8el-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse11"
              />
              <img
                src="/playground_assets/ellipse151365-nlo-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse15"
              />
              <img
                src="/playground_assets/ellipse121365-1ne-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse12"
              />
              <img
                src="/playground_assets/ellipse131365-neh-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse13"
              />
              <img
                src="/playground_assets/ellipse141365-xdq-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse14"
              />
            </div>
            <div className="landing-frame55">
              <img
                src="/playground_assets/ellipse101365-s55q-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1001"
              />
              <img
                src="/playground_assets/ellipse111365-z7bc-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1101"
              />
              <img
                src="/playground_assets/ellipse151365-oe96-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1501"
              />
              <img
                src="/playground_assets/ellipse121365-vly8-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1201"
              />
              <img
                src="/playground_assets/ellipse131365-p63-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1301"
              />
              <img
                src="/playground_assets/ellipse141365-7bz-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1401"
              />
            </div>
            <div className="landing-frame56">
              <img
                src="/playground_assets/ellipse101365-bb4-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1002"
              />
              <img
                src="/playground_assets/ellipse111365-f1oe-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1102"
              />
              <img
                src="/playground_assets/ellipse151365-jote-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1502"
              />
              <img
                src="/playground_assets/ellipse121365-ilwf-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1202"
              />
              <img
                src="/playground_assets/ellipse131365-3phr-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1302"
              />
              <img
                src="/playground_assets/ellipse141365-xg3-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1402"
              />
            </div>
            <div className="landing-frame57">
              <img
                src="/playground_assets/ellipse101365-na76-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1003"
              />
              <img
                src="/playground_assets/ellipse111365-rfg8-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1103"
              />
              <img
                src="/playground_assets/ellipse121365-pjd-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1203"
              />
              <img
                src="/playground_assets/ellipse131365-rwo-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1303"
              />
              <img
                src="/playground_assets/ellipse141365-aoav-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1403"
              />
              <img
                src="/playground_assets/ellipse151365-dzen-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1503"
              />
            </div>
            <div className="landing-frame581">
              <img
                src="/playground_assets/ellipse101365-1hkb-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1004"
              />
              <img
                src="/playground_assets/ellipse111365-a1ar-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1104"
              />
              <img
                src="/playground_assets/ellipse151365-s0v1-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1504"
              />
              <img
                src="/playground_assets/ellipse121365-6pji-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1204"
              />
              <img
                src="/playground_assets/ellipse131365-cl18-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1304"
              />
              <img
                src="/playground_assets/ellipse141365-5k47-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1404"
              />
            </div>
            <div className="landing-frame59">
              <img
                src="/playground_assets/ellipse101365-a9e-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1005"
              />
              <img
                src="/playground_assets/ellipse111365-jtf5-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1105"
              />
              <img
                src="/playground_assets/ellipse151365-ks7c-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1505"
              />
              <img
                src="/playground_assets/ellipse121365-tbbs-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1205"
              />
              <img
                src="/playground_assets/ellipse131365-9j5l-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1305"
              />
              <img
                src="/playground_assets/ellipse141365-c7tq-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1405"
              />
            </div>
          </div>
        </div>
        <img
          src="/playground_assets/unsplash279xihympyy1365-tng-700w.png"
          alt="unsplash279xIHymPYY1365"
          className="landing-unsplash279x--hym-pyy"
        />
        <div className="landing-group101">
          <div className="landing-frame582">
            <div className="landing-frame541">
              <img
                src="/playground_assets/ellipse101365-gk5r-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1006"
              />
              <img
                src="/playground_assets/ellipse111365-9da-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1106"
              />
              <img
                src="/playground_assets/ellipse151365-7o59-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1506"
              />
              <img
                src="/playground_assets/ellipse121365-jum-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1206"
              />
              <img
                src="/playground_assets/ellipse131365-u8fq-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1306"
              />
              <img
                src="/playground_assets/ellipse141365-yt1c-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1406"
              />
            </div>
            <div className="landing-frame551">
              <img
                src="/playground_assets/ellipse101365-q4k-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1007"
              />
              <img
                src="/playground_assets/ellipse111365-hyya-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1107"
              />
              <img
                src="/playground_assets/ellipse151365-t5wb-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1507"
              />
              <img
                src="/playground_assets/ellipse121365-y57i-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1207"
              />
              <img
                src="/playground_assets/ellipse131365-nf7r-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1307"
              />
              <img
                src="/playground_assets/ellipse141365-v8o-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1407"
              />
            </div>
            <div className="landing-frame561">
              <img
                src="/playground_assets/ellipse101365-a9s-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1008"
              />
              <img
                src="/playground_assets/ellipse111365-fco-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1108"
              />
              <img
                src="/playground_assets/ellipse151365-a5i15-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1508"
              />
              <img
                src="/playground_assets/ellipse121365-iyxdo-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1208"
              />
              <img
                src="/playground_assets/ellipse131365-rb99-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1308"
              />
              <img
                src="/playground_assets/ellipse141365-6cd9-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1408"
              />
            </div>
            <div className="landing-frame571">
              <img
                src="/playground_assets/ellipse101365-66qp-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1009"
              />
              <img
                src="/playground_assets/ellipse111365-8m4b-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1109"
              />
              <img
                src="/playground_assets/ellipse121365-1mbvi-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1209"
              />
              <img
                src="/playground_assets/ellipse131365-a8l-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1309"
              />
              <img
                src="/playground_assets/ellipse141365-c3tr-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1409"
              />
              <img
                src="/playground_assets/ellipse151365-77gb-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1509"
              />
            </div>
            <div className="landing-frame583">
              <img
                src="/playground_assets/ellipse101365-70mr-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1010"
              />
              <img
                src="/playground_assets/ellipse111365-mc2f-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1110"
              />
              <img
                src="/playground_assets/ellipse151365-j6dm-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1510"
              />
              <img
                src="/playground_assets/ellipse121365-7wgk-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1210"
              />
              <img
                src="/playground_assets/ellipse131365-38ym-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1310"
              />
              <img
                src="/playground_assets/ellipse141365-7e2j-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1410"
              />
            </div>
            <div className="landing-frame591">
              <img
                src="/playground_assets/ellipse101365-tcmv-200h.png"
                alt="Ellipse101365"
                className="landing-ellipse1011"
              />
              <img
                src="/playground_assets/ellipse111365-glo8-200h.png"
                alt="Ellipse111365"
                className="landing-ellipse1111"
              />
              <img
                src="/playground_assets/ellipse151365-98y-200h.png"
                alt="Ellipse151365"
                className="landing-ellipse1511"
              />
              <img
                src="/playground_assets/ellipse121365-x5q-200h.png"
                alt="Ellipse121365"
                className="landing-ellipse1211"
              />
              <img
                src="/playground_assets/ellipse131365-rfu-200h.png"
                alt="Ellipse131365"
                className="landing-ellipse1311"
              />
              <img
                src="/playground_assets/ellipse141365-5r9e-200h.png"
                alt="Ellipse141365"
                className="landing-ellipse1411"
              />
            </div>
          </div>
        </div>
        <img
          src="/playground_assets/rectangle131365-hr9u-200h.png"
          alt="Rectangle131365"
          className="landing-rectangle13"
        />
        <div className="landing-indicator">
          <img
            src="/playground_assets/ellipse91365-ydo9-200h.png"
            alt="Ellipse91365"
            className="landing-ellipse9"
          />
          <img
            src="/playground_assets/ellipse91365-46ln-200h.png"
            alt="Ellipse91365"
            className="landing-ellipse91"
          />
          <img
            src="/playground_assets/ellipse91365-z9f0c-200h.png"
            alt="Ellipse91365"
            className="landing-ellipse92"
          />
        </div>
      </div>
    </div>
  );
};
